# -*- coding: utf-8 -*-
HTTP_OK = 200
HTTP_FOUND = 302
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_SERVER_ERROR = 500
HTTP_TEMPORARILY_UNAVAILABLE = 503

'''
1xx OAuth2 相关错误
2xx 其他错误
'''

CODE_OK = 0
CODE_FORBIDDEN = 1
CODE_NOT_FOUND = 2
CODE_UNAUTHORIZED = 3

# https://github.com/idan/oauthlib/blob/16cd3b255b2c86ec7da412357cad899c72d8dbf7/oauthlib/oauth2/rfc6749/errors.py
CODE_TOKEN_EXPIRED = 101
CODE_INSECURE_TRANSPORT = 102
CODE_MISMATCHING_STATE = 103
CODE_MISSING_CODE = 104
CODE_MISSING_TOKEN = 105
CODE_MISSING_TOKEN_TYPE = 106
CODE_INVALID_REDIRECT_URI = 107
CODE_MISSING_REDIRECT_URI = 108
CODE_MISMATCHING_REDIRECT_URI = 109
CODE_MISSING_CLIENT_ID = 110
CODE_INVALID_CLIENT_ID = 111
CODE_ACCESS_DENIED = 112
CODE_UNSUPPORTED_RESPONSE_TYPE = 113
CODE_INVALID_SCOPE = 114
CODE_SERVER_ERROR = 115
CODE_TEMPORARILY_UNAVAILABLE = 116
CODE_INVALID_CLIENT = 117
CODE_INVALID_GRANT = 118
CODE_UNAUTHORIZED_CLIENT = 119
CODE_UNSUPPORTED_GRANT_TYPE = 120
CODE_UNSUPPORTED_TOKEN_TYPE = 121
CODE_INVALID_REQUEST = 122
CODE_TOKEN_INVALID = 123

CODE_INVALID_REQUEST_DATA = 200
CODE_MISSING_FIELD = 201
CODE_UNEXPECTED_VALUE_TYPE = 202
CODE_NOT_LOGIN = 203

CODE_INVALID_USERNAME_OR_PASSWORD = 210
CODE_MOBILE_NUMBER_NOT_EXIST = 211
CODE_MOBILE_NUMBER_EXIST = 212
CODE_INVALID_CITY_CODE = 213
CODE_PASSWORD_INVALID_FORMAT = 214
CODE_URL_INVALID_FORMAT = 215
CODE_INVALID_MOBILE_NUMBER = 221
CODE_INVALID_SMS_CODE = 222
CODE_INVALID_IDENTITY_ID = 227
CODE_STAFF_ALREADY_WORKING = 228
CODE_STAFF_NOT_WORKING = 229
CODE_IDENTITY_ID_EXIST = 234
CODE_INVALID_USER_STATE = 235
CODE_INVALID_QR_CODE = 236
CODE_INVALID_STAFF = 237
CODE_TASK_STATUS_ERROR = 238
CODE_TASK_LOCKED = 239


# SMS服务返回的错误码对应我们的错误码
CODE_SMS_INVALID_PHONE_NUMBER = 240
CODE_SMS_SEND_TOO_MANY_TIMES_TO_ONE_USER = 241
# 上面两个code属于应该告诉用户的错误,其它code属于服务端的失误
CODE_SMS_OTHERS = 242

CODE_DATA_TOO_LONG = 243
CODE_DATA_TOO_SHORT = 244

CODE_INVITED_CODE_NOT_INVALID = 245

CODE_MOBILE_NOT_MATCH_WITH_CURRENT_USER = 246    # 修改密码时，手机不匹配
CODE_INCORRECT_OLD_PASSWORD = 247    # 修改密码时，旧密码不正确
CODE_TASK_NOT_EXISTS = 250
CODE_TASK_ACTION_INVALID = 251

CODE_VERIFY_CODE_NOT_MATCH = 260
CODE_DEFAULT_RECOMMEND_NOT_SET = 261

CODE_CRMHOUSE_INVALID_MOBILE = 270
CODE_CRMHOUSE_INVALID_IDENTITY = 271
CODE_NICKNAME_EXIST = 272
CODE_HOUSE_NOT_EXIST = 273
CODE_USER_IDENTITY_INFO_IS_NULL = 274

CODE_USER_WITHOUT_MAIN_HOUSE = 280  # 用户没有主房屋
CODE_HOUSE_WITHOUT_HOUSEKEEPER = 281  # 房屋无对应管家
CODE_HOUSE_HAVE_HOUSEKEEPER = 286  # 房屋已经有管家
CODE_PROJECT_WITHOUT_KEEPER_FUNCTION = 285
CODE_PROJECT_WITHOUT_KEEPER_IM = 286    # 管家未开通IM

CODE_ALREADY_LOGOUT = 282  # 登出时code已经被登出
CODE_VISIT_CODE_DELETED = 283  # 访客验证码被删除

CODE_THIRD_PARTY_TIMEOUT = 290  # 请求第三方接口超时
CODE_EMPLOYEE_WEALTH_NOT_AVAILABLE = 291  # 暂未开通财富值

CODE_MOBILE_USED_BY_STAFF = 292   # 手机号属于某个员工

CODE_NO_PUSH_ID = 293   # 没有绑定push id

CODE_DUPLICATED_RECORDS = 300  # 重复的记录存在时提示

CODE_CHECK_IDENTITY_OK = 301  # 检查身份证号，身份证号正常无重复
CODE_CHECK_IDENTITY_EXPIRED = 302  # 检查身份证号，超时回到首页
CODE_CHECK_IDENTITY_NOT_FOUND = 303  # 检查身份证号，员工不存在

CODE_GET_RONGYUN_TOKEN_FAIL = 304  # 获取融云token失败

CODE_INFO_NOT_MATCH = 305  # 用户的信息与期望的不匹配

CODE_CLEANING_TASK_ERROR = 320  # 保洁系统

CODE_BAD_REQUEST = 400

CODE_RATE_LIMIT = 600    # 接口频率限制
CODE_LOGIN_FAIL_LIMIT = 601

CODE_CAPTCHA_PIC_CODE_REQUIRED = 700    # 需要校验图片验证码
CODE_CAPTCHA_PIC_CODE_FAILED = 701

CODE_EPAY_ERROR = 710
CODE_PAYMENT_ERROR = 711

CODE_PROJECT_NOT_ONLINE = 720  # 项目未上线
CODE_PROJECT_OUT_DATE = 721  # 项目上线超过半年

CODE_BU6_REQUEST_ERROR = 730

CODE_INVALID_ARREAR_DATA = 740  # 欠费已经变更

# 8xx module perm error
CODE_MODULE_NOT_AVAILABLE = 800

CODE_INTERNAL_SERVER_ERROR = 999
CODE_OTHER = 1000


CODE_POST_DELETED = 1100  # 帖子被软删了


class RPCCodes(object):
    # PRC 响应错误码
    # 模仿 HTTP 状态码
    # 请不要使用 1100 - 1300 之间的错误码，这两个
    # 部分已经被征用了
    CLIENT_ERROR = 1100
    # Some more specific client errors
    SERVER_ERROR = 1200
    # Some more specific server errors
